navbar:
  visiable: auto # always, auto
  logo: # choose [img] or [icon + title]
    img:
    icon:
    title:
  menu:
    - name: 首页
      icon: fas fa-rss
      url: /
    - name: 分类
      icon: fas fa-folder-open
      url: categories/
    - name: 标签
      icon: fas fa-tags
      url: tags/
    - name: 归档
      icon: fas fa-archive
      url: archives/
    - name: 关于
      icon: fas fa-info-circle
      url: about/
  search: 搜索 # Search bar placeholder
site_footer:
  # layout of footer: [aplayer, social, license, info, copyright]
  layout: [social, hello]
  social:
    - icon: fab fa-github
      url: https://github.com/liuqh0609
  br: '<br>'
  hello: '你我山巅自相逢，予你与我遇清风'
# ============================cover=============================
cover:
  height_scheme: full # full, half
  layout_scheme: search # blank (留白), search (搜索), dock (坞), featured (精选), focus (焦点)
  display:
    home: true
    archive: true
    others: false # can be written in front-matter 'cover: true'
  background: https://qiniu.lqh.kim/banner1.jpeg
  # background: https://bing.ioliu.cn/v1/rand?w=1920&h=1200
  logo: # https://qiniu.lqh.kim/avatar.jpeg
  title: '火热'
  subtitle: '你我山巅自相逢，予你与我遇清风'
  search: &nbsp;&nbsp; 所想即所达 # search bar placeholder
  features:
    # - name:
    #   icon: #
    #   img: http://qiniu.lqh.kim/%E9%A6%96%E9%A1%B5.png
    #   url: /

############################### Cover ############################### > end

article:
  # 文章列表页面的文章卡片布局方案
  preview:
    scheme: landscape # landscape
    # pin icon for post
    pin_icon: https://cdn.jsdelivr.net/gh/twitter/twemoji@13.0/assets/svg/1f4cc.svg
    # auto generate title if not exist
    auto_title: true # false, true
    # auto generate excerpt if not exist
    auto_excerpt: true # false, true
    # show split line or not
    line_style: dashed # hidden, solid, dashed, dotted
    # show readmore button
    readmore: auto # auto, always
  # 文章详情页面的文章卡片本体布局方案
  body:
    # 文章顶部信息
    # 从 meta_library 中取
    top_meta: [author, category, date, counter]
    footer_widget:
      # 版权声明组件 (for layout: post)
      copyright:
        enable: true
        permalink: '本文永久链接：'
        content:
          - '如需转载博客，请联系作者授权'
          - permalink
    # 文章底部信息
    # 从 meta_library 中取
    bottom_meta: [updated]
    # meta library
    meta_library:
      # 默认文章作者（可在 front-matter 中覆盖）
      author:
        avatar: http://qiniu.lqh.kim/avatar.jpeg
        name: 火热
        url: /blogs/
      # 文章创建日期
      date:
        icon: fas fa-calendar-alt
        title: ''
        format: 'll' # 日期格式 http://momentjs.com/docs/
      # 文章更新日期
      updated:
        icon: fas fa-edit
        title: ''
        format: 'll' # 日期格式 http://momentjs.com/docs/
      # 文章分类
      category:
        icon: fas fa-folder-open
      # 文章浏览计数
      counter:
        icon: fas fa-eye
        unit: '次浏览'
      # 文章评论数量：只支持 valine
      valinecount:
        icon: fas fa-comment-dots
        desc:
          '' # 条评论
          # 文章字数和阅读时长
      wordcount:
        icon_wordcount: fas fa-keyboard
        icon_duration: fas fa-hourglass-half
      # 文章标签
      tags:
        icon: fas fa-hashtag
# ============侧边栏===================
sidebar:
  # 主页、分类、归档等独立页面
  for_page: [blogger, category, tagcloud, qrcode]
  # layout: docs/post 这类文章页面
  for_post: [toc]
  # 侧边栏组件库
  widget_library:
    # ---------------------------------------
    # blogger info widget
    blogger:
      class: blogger
      display: [desktop, mobile] # [desktop, mobile]
      avatar: https://qiniu.lqh.kim/avatar.jpeg
      shape: rectangle # circle, rectangle
      url: /about/
      title: 火热
      subtitle: 时间会见证一切
      jinrishici: true # Poetry Today. You can set a string, and it will be displayed when loading fails.
      social:
        - icon: fas fa-envelope
          url: mailto:528851597@qq.com
        - icon: fab fa-github
          url: https://github.com/liuqh0609/
    # ---------------------------------------
    # toc widget (valid only in articles)
    toc:
      class: toc
      display: [desktop, mobile] # [desktop, mobile]
      header:
        icon: fas fa-list
        title: 本文目录
      list_number: false
      min_depth: 2
      max_depth: 5
    # ---------------------------------------
    # category widget
    category:
      class: category
      display: [desktop] # [desktop, mobile]
      header:
        icon: fas fa-folder-open
        title: 文章分类
        url: /blog/categories/
    # ---------------------------------------
    # tagcloud widget
    tagcloud:
      class: tagcloud
      display: [desktop, mobile] # [desktop, mobile]
      header:
        icon: fas fa-tags
        title: 热门标签
        url: /blog/tags/
      min_font: 14
      max_font: 24
      color: true
      start_color: '#73d13d'
      end_color: '#ff7875'
    donate:
      class: qrcode
      display: [desktop, mobile] # [desktop, mobile]
      height: 64px # Automatic height if not set
      images:
        - http://qiniu.lqh.kim/wx.jpg
comments:
  service: valine
  valine:
    # js: https://cdn.jsdelivr.net/npm/valine@1.4/dist/Valine.min.js
    path: # 全局评论地址 目前设置全局评论地址后visitor失效,这是valine的问题
    placeholder: 快来评论吧~ # 评论占位提示
    # 其他配置项按照yml格式继续填写即可 除了 [el path placeholder emojiCDN emojiMaps] 选项
    appId: 5HgnrLHlnXjqz9e8qU8e1b5x-gzGzoHsz
    appKey: Qqz20xjsnlxX7bNVYAkEOrz8
color_scheme:
  # ------------
  # 通用颜色
  common:
    # 主题色
    theme: '#40a9ff'
    # 链接色
    link: '#40a9ff'
    # 按钮色
    button: '#40a9ff'
    # 鼠标放到交互元素上时的色
    hover: '#ff5722'
    # 主题色块内部的文字颜色
    inner: '#fff'
    # 选中区域文字的背景颜色
    selection: 'alpha(#2196f3, 0.2)'
